### ISSUE TITLE
Autocompletion for JSON loadable things

### ISSUE THREAD

**Issue by vatai** [Spin-Chemistry-Labs/radicalpy#7]
E.g. constants should be autocompletable

**Comment by vatai** [comment]
Something like this could also work for some return values such as:
- `MARY`,
- `anisotropy` (?),
- `Bhalf_fit`,
- `yield_anisotropy`

**Comment by vatai** [comment]
- inherit from `float` and
- override `__new__` as follows:
```python
class Constant(float):
    def __new__(cls, some_arg=None):
        obj = float.__new__(cls, 10)
        obj._some_arg = some_arg
        return obj


const = Constant(some_arg="Hi")
print(const)
print(100.0 + float(const))
print(100.0 + const)
print(const._some_arg)
```

**Comment by vatai** [comment]
- list molecules
- gamma_mT(isotope), multiplicity(isotope)

e = Isotope("E")
e.gamma(mT)
e.gamma(MHz)
e.multiplicity
e.spin_number
print(e) # "E"
print(e.details) # dict, or namespace

so probably need an `Isotope` class...

**Comment by vatai** [comment]
Auto-completion won't work for isotopes because some (most?) of their names start with a number, which is not a valid first character for an identifier. We can have `isotope.E` but we can't have `isotope.1H` -- this simply allowed in the `python` language. Instead I'm aiming for a class which has methods (or rather properties) like `H_iso1.gamma_mT`, `H_iso1.multiplicity`, `H_iso1.spin_quantum_number` etc

**Comment by vatai** [comment]
@lmantill  would be ok to move the function which converts multiplicity to spin quantum number, from utils.py to the new `Isotope` class (in data.py)? spin<-> multiplicity conversion is tied to isotopes, no?

One of the issues I'm considering moving it is the cyclic dependency it caused between utils.py and data.py after moving the `Molecule` class to data.py. With `Molecule` class moved to data.py, `Molecule` wants to use `data.isotropic()` and `data.spin_quantum_number()`... but util.py has a bunch of references to `data.constants`... ergo a cyclic dependency.

**Comment by lmantill** [comment]
Lewis approves
