### ISSUE TITLE
Document and clean up data.py

### ISSUE THREAD

**Issue by vatai** [Spin-Chemistry-Labs/radicalpy#71]

**Comment by vatai** [comment]
- [x] `E.gamma(mT)` (kinda, will do with `pint`)
- [x] `E.gamma(MHz)` (will do with `pint`)
- [x] `E.multiplicity`
- [ ] list molecules
- [ ] `E = Isotope("E")` (currently `Isotope("E", {..data..})`)
- [ ] `E.name # -> "E"`
- [ ] `E.spin_number`
- [ ] `print(e) # "E"`
- [ ] `print(e.details) # dict, or namespace`

**Comment by vatai** [comment]
Usage of `data` module:
- `estimations`: `constants` and `gamma_mT`
- `simulations`:
  - `gamma_mT`, `multiplicity` moved inside `Isotope`
  - `pauli` move from `data.py`
  - `isotropic` - ??? move into molecule? (@lmantill what do you think?)

**Comment by lmantill** [comment]
Moving `isotropic` to molecule makes sense as it is only used for the HFC tensors.
